version: '3.8'

services:
  website:
    image: "polaris:dev"
    build:
      context: .
      dockerfile: Dockerfile
    restart: on-failure
    volumes:
      - .:/home/node
    ports:
      - 3000:3000
